name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/javascript-action@v1.0.1
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
         
